version: '3.8'

services:
  api:
    build:
      context: ./Api
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      DB_HOST: mysql
      DB_DATABASE: invenschool
      DB_USERNAME: invenschool
      DB_PASSWORD: secret
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: invenschool
      MYSQL_USER: invenschool
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootsecret
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
