<?php

namespace Tests\Feature;

use App\Models\Barang;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class BarangTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp();

        $this->seed(\Database\Seeders\RoleSeeder::class);
        $this->seed(\Database\Seeders\LokasiSeeder::class);
        $this->seed(\Database\Seeders\KategoriDanaSeeder::class);
        $this->seed(\Database\Seeders\KategoriBarangSeeder::class);
        $this->seed(\Database\Seeders\UserSeeder::class);
    }

    private function katu(): User
    {
        return User::where('username', 'katu')->first();
    }

    private function sarpras(): User
    {
        return User::where('username', 'sarpras')->first();
    }

    private function kepsek(): User
    {
        return User::where('username', 'kepsek')->first();
    }

    private function kaprodi(): User
    {
        return User::where('username', 'kaprodi_rpl')->first();
    }

    private function validPayload(): array
    {
        return [
            'nama_barang' => 'Komputer',
            'spesifikasi' => 'Intel i5, RAM 8GB',
            'kategori_dana_id' => \App\Models\KategoriDana::first()->id,
            'kategori_barang_id' => \App\Models\KategoriBarang::first()->id,
            'lokasi_id' => \App\Models\Lokasi::first()->id,
            'kondisi_umum' => 'Baik',
        ];
    }

    public function test_unauthenticated_cannot_access(): void
    {
        $this->getJson('/api/barang')->assertStatus(401);
        $this->postJson('/api/barang', $this->validPayload())->assertStatus(401);
    }

    public function test_katu_can_create(): void
    {
        $response = $this->actingAs($this->katu())->postJson('/api/barang', $this->validPayload());

        $response->assertStatus(201)
            ->assertJsonPath('data.nama_barang', 'Komputer')
            ->assertJsonStructure(['data' => ['id', 'kode_barang', 'nama_barang', 'stok_total']]);
    }

    public function test_sarpras_can_create(): void
    {
        $response = $this->actingAs($this->sarpras())->postJson('/api/barang', $this->validPayload());

        $response->assertStatus(201);
    }

    public function test_kepsek_cannot_create(): void
    {
        $response = $this->actingAs($this->kepsek())->postJson('/api/barang', $this->validPayload());

        $response->assertStatus(403);
    }

    public function test_kaprodi_cannot_create(): void
    {
        $response = $this->actingAs($this->kaprodi())->postJson('/api/barang', $this->validPayload());

        $response->assertStatus(403);
    }

    public function test_kode_barang_is_auto_generated_not_from_request(): void
    {
        $response = $this->actingAs($this->katu())->postJson('/api/barang', 
            $this->validPayload() + ['kode_barang' => 'MANUAL-001']
        );

        $response->assertStatus(201);
        $kode = $response->json('data.kode_barang');
        $this->assertNotNull($kode, 'kode_barang should be auto-generated by trigger, got null');
        $this->assertStringStartsNotWith('MANUAL', $kode);
    }

    public function test_stok_fields_not_accepted_in_request(): void
    {
        $response = $this->actingAs($this->katu())->postJson('/api/barang',
            $this->validPayload() + ['stok_baik' => 100, 'stok_rusak' => 10, 'stok_total' => 110]
        );

        $response->assertStatus(201);
        $this->assertEquals(0, $response->json('data.stok_baik'));
        $this->assertEquals(0, $response->json('data.stok_rusak'));
        $this->assertEquals(0, $response->json('data.stok_total'));
    }

    public function test_katu_can_read_all(): void
    {
        $this->actingAs($this->katu())->postJson('/api/barang', $this->validPayload());

        $response = $this->actingAs($this->katu())->getJson('/api/barang');

        $response->assertStatus(200)
            ->assertJsonStructure(['data', 'meta', 'links']);
    }

    public function test_all_roles_can_read(): void
    {
        $this->actingAs($this->katu())->postJson('/api/barang', $this->validPayload());

        foreach (['kepsek', 'sarpras', 'kaprodi_rpl'] as $username) {
            $user = User::where('username', $username)->first();
            $response = $this->actingAs($user)->getJson('/api/barang');
            $response->assertStatus(200);
        }
    }

    public function test_katu_can_update(): void
    {
        $barang = $this->actingAs($this->katu())->postJson('/api/barang', $this->validPayload())->json('data');

        $payload = $this->validPayload();
        $payload['nama_barang'] = 'Komputer Updated';
        $payload['kondisi_umum'] = 'Rusak Ringan';

        $response = $this->actingAs($this->katu())->putJson('/api/barang/' . $barang['id'], $payload);

        $response->assertStatus(200)
            ->assertJsonPath('data.nama_barang', 'Komputer Updated')
            ->assertJsonPath('data.kondisi_umum', 'Rusak Ringan');
    }

    public function test_update_does_not_change_stok(): void
    {
        $barang = $this->actingAs($this->katu())->postJson('/api/barang', $this->validPayload())->json('data');

        $response = $this->actingAs($this->katu())->putJson('/api/barang/' . $barang['id'], 
            $this->validPayload() + ['stok_baik' => 999, 'stok_rusak' => 999]
        );

        $response->assertStatus(200);
        $this->assertEquals(0, $response->json('data.stok_baik'));
        $this->assertEquals(0, $response->json('data.stok_rusak'));
    }

    public function test_non_katu_cannot_update(): void
    {
        $barang = $this->actingAs($this->katu())->postJson('/api/barang', $this->validPayload())->json('data');

        foreach (['kepsek', 'kaprodi_rpl'] as $username) {
            $user = User::where('username', $username)->first();
            $response = $this->actingAs($user)->putJson('/api/barang/' . $barang['id'], $this->validPayload());
            $response->assertStatus(403);
        }
    }

    public function test_katu_can_soft_delete(): void
    {
        $barang = $this->actingAs($this->katu())->postJson('/api/barang', $this->validPayload())->json('data');

        $response = $this->actingAs($this->katu())->deleteJson('/api/barang/' . $barang['id']);

        $response->assertStatus(200);

        $this->assertEquals('Dihapus', Barang::find($barang['id'])->status_aktif);
    }

    public function test_non_katu_cannot_delete(): void
    {
        $barang = $this->actingAs($this->katu())->postJson('/api/barang', $this->validPayload())->json('data');

        foreach (['kepsek', 'sarpras', 'kaprodi_rpl'] as $username) {
            $user = User::where('username', $username)->first();
            $response = $this->actingAs($user)->deleteJson('/api/barang/' . $barang['id']);
            $response->assertStatus(403);
        }
    }

    public function test_riwayat_stok_returns_paginated_data(): void
    {
        $barang = $this->actingAs($this->katu())->postJson('/api/barang', $this->validPayload())->json('data');

        $response = $this->actingAs($this->katu())->getJson('/api/barang/' . $barang['id'] . '/riwayat-stok');

        $response->assertStatus(200)
            ->assertJsonStructure(['data', 'meta', 'links']);
    }

    public function test_filter_by_lokasi_id(): void
    {
        $lokasi2 = \App\Models\Lokasi::skip(1)->first();
        $this->actingAs($this->katu())->postJson('/api/barang', $this->validPayload());
        $this->actingAs($this->katu())->postJson('/api/barang', array_merge($this->validPayload(), [
            'nama_barang' => 'Meja',
            'lokasi_id' => $lokasi2->id,
        ]));

        $response = $this->actingAs($this->katu())->getJson('/api/barang?lokasi_id=' . $lokasi2->id);
        $response->assertStatus(200);
        $this->assertCount(1, $response->json('data'));
    }

    public function test_kaprodi_scope_only_their_lokasi(): void
    {
        $lokasiKaprodi = \App\Models\Lokasi::where('kode_lokasi', 'RPL')->first();
        $this->actingAs($this->katu())->postJson('/api/barang', $this->validPayload());
        $this->actingAs($this->katu())->postJson('/api/barang', array_merge($this->validPayload(), [
            'nama_barang' => 'Meja TKJ',
            'lokasi_id' => \App\Models\Lokasi::where('kode_lokasi', 'TKJ')->first()->id,
        ]));

        $response = $this->actingAs($this->kaprodi())->getJson('/api/barang');

        $response->assertStatus(200);
        foreach ($response->json('data') as $item) {
            $this->assertEquals($lokasiKaprodi->id, $item['lokasi']['id']);
        }
    }
}
